replicaCount: 1
appName: booking-service
version: v2

image:
  name: booking-service
  tag: task5
  pullPolicy: Never

service:
  create: false
  name: booking-service
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: ENABLE_FEATURE_X
    value: "true"
  - name: SERVICE_VERSION
    value: "v2"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

readinessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
