replicaCount: 1

image:
  name: booking-service
  tag: task5
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: ENABLE_FEATURE_X
    value: "true"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

readinessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
